import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Script from "next/script";
import "./styles/globals.scss";

const inter = Inter({ subsets: ["latin"] });


export const metadata: Metadata = {
  title: "Portifolio - Dandara",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className={inter.className}>
      <Script
        strategy="afterInteractive"
        src="https://www.googletagmanager.com/gtag/js?id=G-F819SS7VTV"
      />
      <Script
        id="google-analytics"
        strategy="afterInteractive"
      >
        {`
          window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());
          gtag('config', 'G-F819SS7VTV');
        `}
      </Script>
        {children}
      </body>
    </html>
  );
}
